import { DisplayObject } from './DisplayObject';
import { IComponent, Graphics } from './Core';
import { MouseEvent } from '../events/MouseEvent';
import { Rectangle } from '../types/Rectangle';
import { Padding } from '../types/Padding';
import { FontStyle } from '../types/FontStyle';
import { BorderStyle } from '../types/BorderStyle';
import { Point } from '../types/Point';
export declare const mergeBound: (bound: Rectangle, offset: Padding, border?: number) => Rectangle;
export declare class Component extends DisplayObject implements IComponent {
    protected enable: boolean;
    protected font: FontStyle;
    protected margin: Padding;
    protected border: BorderStyle;
    protected padding: Padding;
    private _outerBound;
    private _innerBound;
    constructor();
    protected initializeListeners(): void;
    private handleMouseEvent;
    protected onMouseClick(event: MouseEvent): void;
    protected onMouseMove(event: MouseEvent): void;
    protected onMouseEnter(event: MouseEvent): void;
    protected onMouseLeave(event: MouseEvent): void;
    findMouseEventHandler(p: Point): IComponent;
    isPointInPath(p: Point): boolean;
    render(): void;
    onPaint(): void;
    protected drawBackground(g: Graphics): void;
    protected drawBorder(g: Graphics): void;
    beforePaint(g: Graphics): void;
    paint(g: Graphics): void;
    afterPaint(g: Graphics): void;
    measure(): void;
    contains(c: IComponent): boolean;
    getMargin(): Padding;
    setMargin(margin: Padding): void;
    getPadding(): Padding;
    setPadding(padding: Padding): void;
    getBorder(): BorderStyle;
    setBorder(border: BorderStyle): void;
    getEnable(): boolean;
    setEnable(enable: boolean): void;
    get outerBound(): Rectangle;
    set outerBound(val: Rectangle);
    get innerBound(): Rectangle;
    set innerBound(val: Rectangle);
    getFont(): FontStyle;
    setFont(font: FontStyle): void;
    protected get mouseEnabled(): boolean;
    get parent(): IComponent;
    set parent(parent: IComponent);
}
//# sourceMappingURL=Component.d.ts.map